server:
  port: 9001
spring:
  application:
    name: tensquare-base

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp133858g2361qh0fso.mysql.rds.aliyuncs.com:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: ENC(x+RLfp0IqGlHHMuU5k/c6Q==)
    password: ENC(9N0j84xejjkUxmfM+MiaYB0sEfMZWDqY)
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

jasypt:
  encryptor:
    password: ${TENSQUARE_HOME}