server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp133858g2361qh0fso.mysql.rds.aliyuncs.com:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8&useSSL=false
    username: ENC(x+RLfp0IqGlHHMuU5k/c6Q==)
    password: ENC(9N0j84xejjkUxmfM+MiaYB0sEfMZWDqY)
  jpa: 
    database: MySQL
    show-sql: true

jasypt:
  encryptor:
    password: ${TENSQUARE_HOME}

jwt:
  config:
    ttl: 1800000
    key: ${TENSQUARE_HOME}

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    # 模块间跨IP访问
    prefer-ip-address: true
    # 服务提供方配置
    # 服务刷新时间配置，每隔这个时间会主动心跳一次 默认 30s
    lease-renewal-interval-in-seconds: 5
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，默认90s
    # 这个配置一般为服务刷新时间配置的三倍
    lease-expiration-duration-in-seconds: 15
    # 服务消费方配置
    #eureka client刷新本地缓存时间
    #默认30s
    #eureka.client.registryFetchIntervalSeconds=5

feign:
  hystrix:
    enabled: true