server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp133858g2361qh0fso.mysql.rds.aliyuncs.com:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8&useSSL=false
    username: root
    password: Yw19981016
  jpa: 
    database: MySQL
    show-sql: true
