server: 
  port: 9004
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    # 数据源配置
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-bp133858g2361qh0fso.mysql.rds.aliyuncs.com:3306/tensquare_article?useUnicode=true&amp;characterEncoding=UTF8&useSSL=false
      username: ENC(x+RLfp0IqGlHHMuU5k/c6Q==)
      password: ENC(9N0j84xejjkUxmfM+MiaYB0sEfMZWDqY)
      # 初始化时建立物理连接的个数
      initialSize: 5
      # 连接池最小连接数
      minIdle: 5
      # 连接池最大连接数
      maxActive: 1000
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      timeBetweenEvictionRunsMillis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql 必须是一个查询语句,mysql中为 select 'x', oracle中为 select 1 from dual
      validationQuery: SELECT 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnBorrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false
      # 是否缓存preparedStatement,mysql5.5+建议开启
      poolPreparedStatements: true
      # 配置扩展插件,配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙#
      filters: stat,wall,slf4j
      # 当值大于0时poolPreparedStatements会自动修改为true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      要配置统计信息（包括监控信息） time-between-log-stats-millis 输出至日志中，
#      合并多个DruidDataSource的监控数据 use-global-data-source-stat 不可开启，否则启动会报错
#      time-between-log-stats-millis: 300000
      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: '/*'
#        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      # 配置DruidStatViewServlet
#      stat-view-servlet:
        # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
#        enabled: true
#        url-pattern: '/druid/*'
        # IP白名单(没有配置或者为空，则允许所有访问)
#        allow: 127.0.0.1,192.168.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
#        deny: 192.168.0.128
        # 禁用HTML页面上的“Reset All”功能
#        reset-enable: false
        # 登录名
#        login-username: admin
        # 登录密码
#        login-password: admin
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 47.93.11.144
    port: 6379
    password: ENC(+ySWSe9c1nYhQ53OIUd4GyVLd0tdO4fLUP+6/GCOPeg=)
    database: 0
    timeout: 20000

  data:
    mongodb:
      uri: mongodb://article:123456@47.93.11.144:27017/articledb

jasypt:
  encryptor:
    password: ${TENSQUARE_HOME}

logging:
  level:
    root: info
    org:
      hibernate: info

jwt:
  config:
    ttl: 1800000
    key: ${TENSQUARE_HOME}