server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp133858g2361qh0fso.mysql.rds.aliyuncs.com:3306/tensquare_gathering?useUnicode=true&amp;characterEncoding=UTF8&useSSL=false
    username: ENC(x+RLfp0IqGlHHMuU5k/c6Q==)
    password: ENC(9N0j84xejjkUxmfM+MiaYB0sEfMZWDqY)
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.93.11.144
    password: ENC(+ySWSe9c1nYhQ53OIUd4GyVLd0tdO4fLUP+6/GCOPeg=)
    database: 0
    timeout: 20000

jasypt:
  encryptor:
    password: ${TENSQUARE_HOME}